//========= Copyright © 1996-2005, Valve Corporation, All rights reserved. ============//
//
// Purpose: 
//
// $NoKeywords: $
//
//=============================================================================//
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HL_Res.RC
//
#define IDS_LANGUAGE                    1
#define IDS_BORDERLESS_REGFAIL          2
#define IDS_CHAT_IGNORE_MISLINKED       3
#define IDS_CHAT_IGNORE_UNLINKED        4
#define IDS_CREATE_MAPSCHANGED          5
#define IDS_CREATE_LIBLISTBAD           6
#define IDS_SOCKET_CONNECTIONFAILURE    7
#define IDS_PLAYERINFO_NOMEM            8
#define IDS_CHAT_NOCONNECTION           9
#define IDS_CHAT_NOSTREAM               10
#define IDS_CHAT_NOSELECT               11
#define IDS_CONTROLS_DELETE_LINKED      12
#define IDS_CONTROLS_KBLIST_EMPTY       13
#define IDS_CONTROLS_KBLIST_PARSEERROR  14
#define IDS_CONTROLS_KBKEYS_EMPTY       15
#define IDS_CONTROLS_KBKEYS_PARSEERROR  16
#define IDS_CONTROLS_KBKEYS_OVERFLOW    17
#define IDS_PROFILE_COLOR               18
#define IDS_MAIN_NOCAPS                 19
#define IDS_MAIN_INSUFFICIENTCAPS       20
#define IDS_MAIN_REGWNDCLSFAIL          21
#define IDS_MAIN_INSUFFICIENTSOCKETS    22
#define IDS_MAIN_MEMMAPFAILURE          23
#define IDS_PROFILE_NOMEM               24
#define IDS_BTN_STRANGESIZE             25
#define IDS_MAIN_NOUSERMSGS             26
#define IDS_MAIN_NOFILEMAPPING          27
#define IDS_MAIN_NOMEMMAPCONNECT        28
#define IDS_MSG_OVERFLOW                29
#define IDS_MSG_REQTOOBIG               30
#define IDS_MULTI_NOROOMSTATIC          31
#define IDS_MULTI_NOROOMTAB             32
#define IDS_MULTI_NOCHATWINDOW          33
#define IDS_MULTI_NOCHATINPUT           34
#define IDS_MULTI_NOUSERLIST            35
#define IDS_MULTI_NOSERVERLIST          36
#define IDS_MULTI_NOSELECTION           37
#define IDS_MULTI_NOARCHIVE             38
#define IDS_CHAT_USER_NOMEM             39
#define IDS_MULTI_SERVER_NOMEM          40
#define IDS_MULTI_MASTER_BADLISTFILE    41
#define IDS_MULTI_NODIALOG              42
#define IDS_PROFILE_REQUIRED            43
#define IDS_ODCOMBO_REGFAIL             44
#define IDS_ODEDIT_REGFAIL              45
#define IDS_ODLIST_REGFAIL              46
#define IDS_ODSCROLL_REGFAIL            47
#define IDS_ODSLIDER_REGFAIL            48
#define IDS_ODTAB_REGFAIL               49
#define IDS_PROFILE_NICKREMOVEFAIL      50
#define IDS_PROFILE_NOPROFILE           51
#define IDS_QUICK_NOSERVERS             52
#define IDS_QUICK_NOACTIVE              53
#define IDS_README_NOMEM                54
#define IDS_ROOM_BADNAME                55
#define IDS_SINGLE_NOSELECTION          56
#define IDS_SINGLE_CANTSAVE             57
#define IDS_ODLISTBOX_REGFAIL           58
#define IDS_DIB_OPENFAIL                59
#define IDS_MCI_OPENFAIL                60
#define IDS_MCI_GETIDFAIL               61
#define IDS_MCI_WINDOWFAIL              62
#define IDS_MCI_PUTFAIL                 63
#define IDS_MCI_SEEKFAIL                64
#define IDS_MCI_BREAKFAIL               65
#define IDS_MCI_PLAYFAIL                66
#define IDS_MCI_STOPFAIL                67
#define IDS_MCI_CLOSEFAIL               68
#define IDS_CONTROLS_RESTOREFAIL        69
#define IDS_SND_BADNAME                 70
#define IDS_PROFILE_ALLOCFAIL           71
#define IDS_AUDIO_NOPROFILE             72
#define IDS_VIDEO_NOPROFILE             73
#define IDS_CONTROLS_KEYHELP            74
#define IDS_ENDDEMO_URL                 75
#define IDS_ORDER_URL                   76
#define IDS_LOADSAVE_HINT               77
#define IDS_LAUNCHER_BUTTONSIZE         78
#define IDS_MEM_INSUFFICIENT            79
#define IDS_MEM_ALLOCFAIL               80
#define IDS_EVENT_CREATEFAIL            81
#define IDS_OSVER_FAIL                  82
#define IDS_OSVER_OUTDATED              83
#define IDS_OSVER_NTSP3                 84
#define IDS_OSVER_16BIT                 85
#define IDS_BINDING_ACTIONHEADING       86
#define IDS_BINDING_PRIMARYHEADING      87
#define IDS_BINDING_ALTERNATEHEADING    88
#define IDS_BINDING_PROMPT              89
#define IDS_URL_BROWSERFAIL             90
#define IDS_SAVELOAD_TIMECOL            91
#define IDS_SAVELOAD_GAMECOL            92
#define IDS_SAVELOAD_ELAPSEDCOL         93
#define IDS_SERVER_GAMESERVER           94
#define IDS_SERVER_SPEED                95
#define IDS_SERVER_MAP                  96
#define IDS_SERVER_PLAYERS              97
#define IDS_SERVER_MAX                  98
#define IDS_SERVER_GAME                 99
#define IDS_SERVER_NETWORK              100
#define IDS_QUERY_STARTING              101
#define IDS_QUERY_COMPLETED             102
#define IDS_SERVER_REMOVE               103
#define IDS_SERVER_CONNECT              104
#define IDS_SERVER_LANTAG               105
#define IDS_SERVER_INTERNETTAG          106
#define IDS_SERVER_MENU_CONNECT         107
#define IDS_SERVER_MENU_PLAYERINFO      108
#define IDS_SERVER_MENU_RULEINFO        109
#define IDS_SERVER_MENU_FILTER          110
#define IDS_SERVER_MENU_ADDTOFAVORITE   111
#define IDS_SERVER_MENU_REMOVEFROMFAV   112
#define IDS_SERVER_MENU_REMOVE          113
#define IDS_SERVER_MENU_NOPLAYERINFO    114
#define IDS_SERVER_MENU_NOLANPLAYERINFO 115
#define IDS_SAVELOAD_QUICKLISTTEXT      116
#define IDS_SAVELOAD_AUTOLISTITEM       117
#define IDS_PLAYERINFO_NUMBER           118
#define IDS_PLAYERINFO_NAME             119
#define IDS_PLAYERINFO_KILLS            120
#define IDS_PLAYERINFO_TIME             121
#define IDS_PLAYERINFO_SUIT             122
#define IDS_QUICK_REQUEST               123
#define IDS_QUICK_GOTLIST               124
#define IDS_QUICK_CONTACTING            125
#define IDS_QUICK_COMPLETEDSERVER       126
#define IDS_SAVE_NEWCOMMENT             127
#define IDS_SAVE_NEWTIME                128
#define IDS_SAVE_NEWFILETIME            129
#define IDS_DDRAW_FAILEINIT             130
#define IDS_DDRAW_DX4FAIL               131
#define IDS_VIDEO_MODECOL               132
#define IDS_ROOM_NAMECOL                133
#define IDS_ROOM_PEOPLECOL              134
#define IDS_ROOM_SERVERSCOL             135
#define IDS_DDRAW_REQUIRED              136
#define IDS_DLL_LOADFAIL                137
#define IDS_CMDLINE_VTOPTS              138
#define IDS_SAVE_NUMCHANGED             139
#define IDS_BINDINGS_ALLOCFAIL          140
#define IDS_GAMMA_LOADFAIL              141
#define IDS_DDRAW_RESTOREMODEFAIL       142
#define IDS_AUDIO_VOLUME                143
#define IDS_AUDIO_SUITVOL               144
#define IDS_AUDIO_USECD                 145
#define IDS_AUDIO_HIGHQUALITY           146
#define IDS_CFG_VIDHELP                 147
#define IDS_CFG_AUDIOHELP               148
#define IDS_CFG_CONTROLHELP             149
#define IDS_CFG_RETURNTOMAIN            150
#define IDS_CREATEROOM_TITLE            151
#define IDS_CREATEROOM_ROOMNAME         152
#define IDS_CREATEROOM_ROOMTOPIC        153
#define IDS_CREATESERVER_NAME           154
#define IDS_CREATESERVER_MAP            155
#define IDS_CREATESERVER_ROOM           156
#define IDS_CREATESERVER_GAMETYPE       157
#define IDS_CREATESERVER_MAXPLAYERS     158
#define IDS_FILTER_TITLE                159
#define IDS_FILTER_HEADING              160
#define IDS_FILTER_RESPONDING           161
#define IDS_FILTER_RESPONSETIME         162
#define IDS_FILTER_NOTFULL              163
#define IDS_FILTER_NOTEMPTY             164
#define IDS_FILTER_ONFAVORITES          165
#define IDS_FILTER_INCHATROOM           166
#define IDS_FINDPLAYER_TITLE            167
#define IDS_FINDPLAYER_PLAYER           168
#define IDS_FINDPLAYER_SERVER           169
#define IDS_OPTS_CROSSHAIR              170
#define IDS_OPTS_REVERSE                171
#define IDS_OPTS_MLOOK                  172
#define IDS_OPTS_LOOKSPRING             173
#define IDS_OPTS_LOOKSTRAFE             174
#define IDS_OPTS_MFILTER                175
#define IDS_OPTS_JOYSTICK               176
#define IDS_OPTS_CROSSHAIRHELP          177
#define IDS_OPTS_REVERSEHELP            178
#define IDS_OPTS_MLOOKHELP              179
#define IDS_OPTS_LOOKSPRINGHELP         180
#define IDS_OPTS_LOOKSTRAFEHELP         181
#define IDS_OPTS_MFILTERHELP            182
#define IDS_OPTS_JOYSTICKHELP           183
#define IDS_OPTS_SENSITIVITYHELP        184
#define IDS_LOADSAVE_LOADHELP           185
#define IDS_LOADSAVE_SAVEHELP           186
#define IDS_LOADSAVE_RETURN             187
#define IDS_MAIN_RETURNHELP             188
#define IDS_MAIN_NEWGAMEHELP            189
#define IDS_MAIN_TRAININGHELP           190
#define IDS_MAIN_LOADHELP               191
#define IDS_MAIN_LOADSAVEHELP           192
#define IDS_MAIN_CONFIGUREHELP          193
#define IDS_MAIN_READMEHELP             194
#define IDS_MAIN_ORDERHELP              195
#define IDS_MAIN_QUITHELP               196
#define IDS_MAIN_QUICKHELP              197
#define IDS_MAIN_MULTIPLAYERHELP        198
#define IDS_CHAT_PROMPT                 199
#define IDS_NEWGAME_EASYHELP            200
#define IDS_NEWGAME_MEDIUMHELP          201
#define IDS_NEWGAME_DIFFICULTHELP       202
#define IDS_NEWGAME_RETURNHELP          203
#define IDS_NEWPROFILE_TITLE            204
#define IDS_NEWPROFILE_NAME             205
#define IDS_NEWPROFILE_PASSWORD         206
#define IDS_NEWPROFILE_REMEMBER         207
#define IDS_PROFILE_MODEL               208
#define IDS_PROFILE_NICKNAME            209
#define IDS_PROFILE_SELECT              210
#define IDS_PROFILE_PROCEEDHELP         211
#define IDS_PROFILE_RETURNHELP          212
#define IDS_VIDEO_SCREENSIZE            213
#define IDS_VIDEO_GAMMA                 214
#define IDS_VIDEO_GLARE                 215
#define IDS_VIDEO_GAMMAHELP             216
#define IDS_VIDEO_GLAREHELP             217
#define IDS_VIDMODE_WINDOWED            218
#define IDS_VIDMODE_MOUSE               219
#define IDS_VIDMODE_GLLISTHEADER        220
#define IDS_VIDMODE_D3DHEADER           221
#define IDS_VIDSELECT_OPTIONSHELP       222
#define IDS_VIDSELECT_MODESHELP         223
#define IDS_VIDSELECT_RETURNHELP        224
#define IDS_SERVERS_REFRESH             225
#define IDS_PROGRESS_START              226
#define IDS_QUICK_CONTACT               227
#define IDS_QUICK_REQUESTLIST           228
#define IDS_README_NOFILE               229
#define IDS_STATUS_CONNECTING           230
#define IDS_STATUS_CONNECTIONESTABLISHED 231
#define IDS_STATUS_SKIPSERVER           232
#define IDS_STATUS_ELPASEDTIME          233
#define IDS_TRAINING_EXITCURRENT        234
#define IDS_MAIN_QUITPROMPTINGAME       235
#define IDS_MAIN_QUITPROMPT             236
#define IDS_CONTROLS_CANCELPROMPT       237
#define IDS_LOAD_LOADPROMPT             238
#define IDS_LOADSAVE_DELETEPROMPT       239
#define IDS_NEWGAME_NEWPROMPT           240
#define IDS_NICKNAME_ADD                241
#define IDS_PROFILE_CANCELPROMPT        242
#define IDS_SAVE_INGAMEPROMPT           243
#define IDS_SAVE_OVERWRITE              244
#define IDS_VIDEO_BADSETTINGS           245
#define IDS_AUDIO_A3D                   246
#define IDS_BTN_DONE                    247
#define IDS_BTN_CONTROLS                248
#define IDS_BTN_AUDIO                   249
#define IDS_BTN_VIDEO                   250
#define IDS_BTN_CANCEL                  251
#define IDS_BTN_CREATE                  252
#define IDS_BTN_FILTER                  253
#define IDS_BTN_FIND                    254
#define IDS_BTN_RETURN                  255
#define IDS_BTN_NEWGAME                 256
#define IDS_BTN_TRAINING                257
#define IDS_BTN_CONFIGURE               258
#define IDS_BTN_LOADSAVE                259
#define IDS_BTN_LOAD                    260
#define IDS_BTN_MULTIPLAYER             261
#define IDS_BTN_README                  262
#define IDS_BTN_ORDER                   263
#define IDS_BTN_QUIT                    264
#define IDS_BTN_ADVANCED                265
#define IDS_BTN_REVERT                  266
#define IDS_BTN_RESTORE                 267
#define IDS_BTN_DELETE                  268
#define IDS_BTN_SAVE                    269
#define IDS_BTN_LOGIN                   270
#define IDS_BTN_CONNECT                 271
#define IDS_BTN_CREATESV                272
#define IDS_BTN_REFRESH                 273
#define IDS_BTN_ROOM                    274
#define IDS_BTN_EASY                    275
#define IDS_BTN_MEDIUM                  276
#define IDS_BTN_HARD                    277
#define IDS_BTN_YES                     278
#define IDS_BTN_NO                      279
#define IDS_BTN_OK                      280
#define IDS_BTN_OPTIONS                 281
#define IDS_BTN_MODES                   282
#define IDS_BTN_QUICK                   283
#define IDS_PROFILE_LOGO                284
#define IDS_BTN_BROWSE                  285
#define IDS_MULTI_BROWSEHELP            286
#define IDS_BTN_CHAT                    287
#define IDS_MULTI_CHATHELP              288
#define IDS_BTN_LAN                     289
#define IDS_MULTI_LANHELP               290
#define IDS_BTN_CUSTOMIZE               291
#define IDS_MULTI_CUSTOMIZEHELP         292
#define IDS_CREATEROOM_ROOMPASSWORD     293
#define IDS_PLAYERINFO_RULENAME         294
#define IDS_PLAYERINFO_RULEVALUE        295
#define IDS_BTN_SEARCH                  296
#define IDS_BTN_CHATMODE                297
#define IDS_BTN_LISTMODE                298
#define IDS_BTN_EXIT                    299
#define IDS_SERVER_MANUALADD            300
#define IDS_SERVER_REQUESTNEWLIST       301
#define IDS_PLAYERINFO_SERVERNAME       302
#define IDS_PLAYERINFO_SERVERIP         303
#define IDS_PLAYERINFO_SERVERPING       304
#define IDS_PROFILE_FACE                305
#define IDS_PROFILE_SKIN                306
#define IDS_BTN_JOIN                    307
#define IDS_BTN_FINDGAME                308
#define IDS_BTN_START                   309
#define IDS_PROFILE_LOGOCOLOR           311
#define IDS_MULTI_RESUMEHELP            312
#define IDS_MULTI_DISCONNECTHELP        313
#define IDS_BTN_RESUME                  314
#define IDS_BTN_DISCONNECT              315
#define IDS_BTN_ADDSERVER               316
#define IDS_BTN_UPDATE                  317
#define IDS_BTN_INFO                    318
#define IDS_QUICKSTART_TITLE            319
#define IDS_BTN_LISTROOMS               320
#define IDS_BTN_GORE                    321
#define IDS_BTN_AUTOPATCH               322
#define IDS_CONFIGURE_GOREHELP          323
#define IDS_CONFIGURE_AUTOPATCHHELP     324
#define IDS_CHAT_NOSERVERS              325
#define IDS_CHAT_NOPROFILE              326
#define IDS_INIT_DX6REQUIRED            327
#define IDS_WON_VALIDATIONFAIL          328
#define IDS_WON_VALIDATIONFAIL2         329
#define IDS_WON_AUTHOUTOFORDER          330
#define IDS_WON_AUTHPROBLEM             331
#define IDS_WON_ENCRYPTBAD              332
#define IDS_WON_BADPUBLICKEY            333
#define IDS_WON_AUTHNOMEM               334
#define IDS_CD_NEEDCDKEY                335
#define IDS_CD_BADKEY                   336
#define IDS_CD_BADKEYTYPED              337
#define IDS_MD5_HASHFAIL                338
#define IDS_MAIN_REGISTERMSGFAIL        339
#define IDS_CDCHECK_PROMPT              340
#define IDS_SETTINGS_SERVERTYPEINVALID  341
#define IDS_TOKEN_EXPECTLEFTBRACE       342
#define IDS_TOKEN_EXPECTRIGHTBRACE      343
#define IDS_MULTI_ADDIPUNRESOLVABLE     344
#define IDS_CHATCTRL_NOMEM              345
#define IDS_CHATCTRL_NOTEXTMEM          346
#define IDS_CHATCTRL_WINREGFAIL         347
#define IDS_PROFILE_DEFAULTMISSING      348
#define IDS_QUICK_NOMASTER              349
#define IDS_QUICK_USINGPREVIOUSLIST     350
#define IDS_CHAT_NOROOMLIST             351
#define IDS_SAVELOAD_NUMBEROFGAMESCHANGED 352
#define IDS_MAIN_EXITMULTIPLAYERPROMPT  353
#define IDS_CD_ENTERPROMPT              354
#define IDS_MULTISELECT_EXITGAMEPROMPT  355
#define IDS_MULTI_ADDSERVERPROMPT       356
#define IDS_ROOM_NEEDPASS               357
#define IDS_SAVE_CANTSAVE               358
#define IDS_SAVE_OVERWRITEPROMPT        359
#define IDS_SAVE_DELETEPROMPT           360
#define IDS_AUTH_INUSE                  361
#define IDS_AUTH_BADACCOUNT             362
#define IDS_AUTH_BADREQ                 363
#define IDS_AUTH_BADCERTIFICATE         364
#define IDS_AUTH_BADEXE                 365
#define IDS_AUTH_BADCERTIFICATE2        366
#define IDS_AUTH_BADLOOKUP              367
#define IDS_AUTH_BADBITS                368
#define IDS_AUTH_CORRUPT                369
#define IDS_AUTH_INVALIDACCOUNT         370
#define IDS_CHAT_STATUSUNCONNECTED      371
#define IDS_CHAT_WONCONNECT             372
#define IDS_CHAT_USERENTER              373
#define IDS_CHAT_USERLEFT               374
#define IDS_ENG_STARTING                375
#define IDS_SERVERS_SEARCHING           376
#define IDS_SERVERS_LISTREC             377
#define IDS_SERVERS_CONNECTING          378
#define IDS_SERVERS_REQUESTINFO         379
#define IDS_ROOM_CREATENOTICE           380
#define IDS_ROOM_CREATEPROMPTTITLE      381
#define IDS_SAVE_TIMEHEADING            382
#define IDS_SAVE_GAMEHEADING            383
#define IDS_SAVE_ELAPSEDHEADING         384
#define IDS_SAVE_NEWCAPTION             385
#define IDS_SAVE_NEWGAMETXT             386
#define IDS_SAVE_FILETIME               387
#define IDS_STATUS_CONNECTINGNOTIME     388
#define IDS_MULTI_CHATROOMCAPTION       389
#define IDS_GORE_CHECKBOX               390
#define IDS_GORE_HELP                   391
#define IDS_GORE_PWPROMPT1              392
#define IDS_GORE_PWPROMPT2              393
#define IDS_GORE_PWMISMATCHED           394
#define IDS_GORE_BADPW                  395
#define IDS_BTN_ADVANCEDSVR             396
#define IDS_OPTS_AUTOAIM                397
#define IDS_OPTS_AUTOAIMHELP            398
#define IDS_BTN_PREVIEWS                399
#define IDS_MAIN_PREVIEWSHELP           400
#define IDS_SECONDS_LEFT                401
#define IDS_MEDIA_PREVIEWURL            402
#define IDS_ADVANCEDSVR_PAGE            403
#define IDS_EMPTY                       404
#define IDS_MULTI_TYPE                  405
#define IDS_MULTI_LAN                   406
#define IDS_MULTI_ISDN                  407
#define IDS_MODEM56K                    408
#define IDS_MODEM28K                    409
#define IDS_OPTS_HIMODELS               410
#define IDS_OPTS_HIMODELSHELP           411
#define IDS_CHAT_SOCKETERROR            412
#define IDS_CHAT_RECONNECTFAIL          413
#define IDS_CHAT_RECONNECTSUCCESS       414
#define IDS_CHAT_JOINFAILED             415
#define IDS_BTN_WON                     416
#define IDS_WON_URL                     417
#define IDS_AUDIO_CDHINT                418
#define IDS_PREVIOUS                    419
#define IDS_NEXT                        420
#define IDS_MODEM33K                    421
#define IDS_MODEM14K                    422
#define IDS_ROOM_PERMANENT              423
#define IDS_ROOM_USER                   424
#define IDS_MULTI_DONEHELP              425
#define IDS_MULTI_WONHELP               426
#define IDS_AUDIO_EAX                   427
#define IDS_GL_NOMODE                   428
#define IDS_D3D_NOMODE                  429
#define IDS_VID_NOMODE                  430
#define IDS_VID_RESELECT                431
#define IDS_VID_INITFAIL                432
#define IDS_NET_WONCONNFAIL             433
#define IDS_NET_CORRUPT                 434
#define IDS_CDKEY_BAD                   435
#define IDS_MULTI_REFRESH               436
#define IDS_CHAT_NOROOM                 437
#define IDS_RUN_PATCH                   438
#define IDS_WON_AUTHFAILURE             439
#define IDS_WON_LOGIN                   440
#define IDS_LOGO_SIZEMISMATCH           441
#define IDS_LOGO_OVERSIZED              442
#define IDS_LOGO_POWEROF2               443
#define IDS_MODEM_CUSTOM                444
#define IDS_MODEM_RATE                  445
#define IDS_REGISTRY_UPDATE             446
#define IDS_CHAT_JOIN                   447
#define IDS_CHAT_FLOOD                  448
#define IDS_CHAT_SEARCH                 449
#define IDS_CHAT_NOINFO                 450
#define IDS_CHAT_NOFIND                 451
#define IDS_CHAT_FIND                   452
#define IDS_CHAT_NOAUTH                 453
#define IDS_CHAT_NODIR                  454
#define IDS_CHAT_NOSUCHROOM             455
#define IDS_CHAT_ROOMFULL               456
#define IDS_CREATESV_NOADVANCED         457
#define IDS_WON_CDINUSE                 459
#define IDS_CHAT_JOINHINT               460
#define IDS_WON_BANNED                  461
#define IDS_CONTENT_NOMULTIPLAYER       462
#define IDS_PATCH_ERROR                 463
#define IDS_PATCH_NOUTIL                464
#define IDS_PATCH_FAIL                  465
#define IDS_PATCH_BADINSTALL            466
#define IDS_CONNECT_FAILURE             467
#define IDS_MULTI_NEEDPASSWORD          468
#define IDS_VID_HINT                    469
#define IDS_MULTI_LOGODISCONNECT        470
#define IDS_3D_WARNING                  471
#define IDS_3DSITE_URL                  472
#define IDS_WON_MODIFIED                473
#define IDS_ADVANCEDMP_OFFSETS          474
#define IDS_AUDIO_OFFSET                475
#define IDS_CONFIGURE_OFFSET            476
#define IDS_CREATEROOM_OFFSET           477
#define IDS_CREATESERVER_OFFSET         478
#define IDS_GAMEOPTIONS_OFFSET          479
#define IDS_HLMAIN_OFFSET               480
#define IDS_KEYBOARD_OFFSET             481
#define IDS_LAN_OFFSET                  482
#define IDS_LOAD_OFFSET                 483
#define IDS_NETGAMEDLG_OFFSET           484
#define IDS_NEWGAMEDLG_OFFSET           485
#define IDS_PLAYERINFODLG_OFFSET        486
#define IDS_PLAYERPROFILEDLG_OFFSET     487
#define IDS_PROMPT_OFFSET               488
#define IDS_ROOM_OFFSET                 489
#define IDS_VIDEODLG_OFFSET             490
#define IDS_VIDEOMODEDLG_OFFSET         491
#define IDS_VIDSELECTDLG_OFFSET         492
#define IDS_UPDATERREGISTRYINSTALLDIR   493
#define IDS_SPANISH                     494
#define IDS_FRENCH                      495
#define IDS_OPTS_JLOOKHELP              496
#define IDS_OPTS_JLOOK                  497
#define IDS_GERMAN                      498
#define IDS_CONNECT_PROTOCOLBAD         499
#define IDS_SERVER_MENU_QUICK           500
#define IDS_DECAL_LIMIT                 501
#define IDS_SPRITE_SKIP                 502
#define IDS_MODEL_NAME                  503
#define IDS_FILTER_BYGAME               504
#define IDS_BTN_SETINFO                 505
#define IDS_MODLIST_TYPE                506
#define IDS_MODLIST_NAME                507
#define IDS_MODLIST_VERSION             508
#define IDS_MODLIST_SIZE                509
#define IDS_MODLIST_RATING              510
#define IDS_MODLIST_INSTALLED           511
#define IDS_MODLIST_SERVERS             512
#define IDS_MODLIST_PLAYERS             513
#define IDS_MOD_DOWNLOADING             514
#define IDS_MOD_DLSIZEMB                515
#define IDS_MOD_DLSIZEKB                516
#define IDS_MOD_DLSTATUS                517
#define IDS_MOD_TIME                    518
#define IDS_MOD_CONNECT                 519
#define IDS_MOD_GETTINGSIZE             520
#define IDS_MOD_DLSTATUSSHORT           521
#define IDS_MOD_NOFILES                 522
#define IDS_MOD_NOLIBLIST               523
#define IDS_INTERNET_CURRENTTOTALS      524
#define IDS_SERVER_REFRESH              525
#define IDS_CONNECT_NEEDMOD             526
#define IDS_MOD_REMOTEOPENFAIL          527
#define IDS_MOD_LOCALOPENFAIL           528
#define IDS_BTN_CUSTOMGAME              529
#define IDS_MAIN_CUSTOMHELP             530
#define IDS_BTN_ACTIVATE                531
#define IDS_BTN_INSTALL                 532
#define IDS_BTN_DETAILS                 533
#define IDS_BTN_VISIT                   534
#define IDS_BTN_REFRESHMODS             535
#define IDS_BTN_DEACTIVATE              536
#define IDS_MOD_INFO                    537
#define IDS_YES                         538
#define IDS_NO                          539
#define IDS_UPDATE                      540
#define IDS_MODREQ_TITLE                541
#define IDS_DOWNLOAD_WARNING            542
#define IDS_WARN_CHECKPROMPT            543
#define IDS_MOD_VERSION                 544
#define IDS_MOD_REINSTALL               545
#define IDS_WARN_TITLE                  546
#define IDS_MOD_ENGINEVERSION           547
#define IDS_MOD_CONNVERSION             548
#define IDS_CONNHLVERSION               549
#define IDS_MOD_NOTINSTALLED            550
#define IDS_REFRESH_SERVERS             552
#define IDS_DEDICATED                   553
#define IDS_MOD_MODVERSION              554
#define IDS_CONN_FULL                   555
#define IDS_MOD_UNZIP                   556
#define IDS_FAVSVRS_CORRUPT             557
#define IDS_MULTI_DSL                   558
#define IDS_MULTI_VIDCHANGE             559
#define IDS_CDKEY_NEEDVALID             560
#define IDS_OPTS_CONSOLE                561
#define IDS_OPTS_CONSOLEHELP            562

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
